new function(){
	importPackage(net.ion.icrawler) 
	importPackage(net.ion.icrawler.pipeline) 
	importPackage(net.ion.icrawler.processor) 
	importPackage(net.ion.icrawler.scheduler) 
	
	this.scheduler = function(){
		return new MaxLimitScheduler(new QueueScheduler(), 10) ;
	}, 
	
	this.processor = function(){
		var site = Site.me().addStartUrl("http://bleujin.tistory.com/")
		var urlPattern = "(" + "http://bleujin.tistory.com/\\d+".replace(".", "\\.").replace("*", "[^\"'#]*") + ")";
		
		return new PageProcessor({
			process : function(page){
				var requests = page.getHtml().links().regex(urlPattern).targets();
				page.addTargets(requests); // add urls to fetch
				page.putField("title", page.getHtml().xpath("//h2[@class='title']/a/text()")); // extract by XPath
				page.putField("date", page.getHtml().xpath("//div[@class='infor']//span[@class='date']/regex('\\d+\\/\\d+\\/\\d+\\s+\\d+:\\d+')"));
				page.putField("content", page.getHtml().smartContent()); // extract by Readability
			}, 
			
			getSite : function(){
				return site ;
			}
		});
	}, 
	
	this.handle = function(){
		var spider = Spider.create(this.processor()).scheduler(this.scheduler());
		spider.getSite().setSleepTime(50);

		spider.run();	
	}
} ;