new function(){
	importPackage(net.ion.icrawler) 
	importPackage(net.ion.icrawler.pipeline) 
	importPackage(net.ion.icrawler.processor) 
	importPackage(net.ion.icrawler.scheduler) 
	
	this.scheduler = function(){
		return new MaxLimitScheduler(new QueueScheduler(), 10) ;
	}, 
	
	this.processor = function(){
		var site = Site.me().addStartUrl("http://bleujin.tistory.com/")
		var urlPattern = "(" + "http://bleujin.tistory.com/*".replace(".", "\\.").replace("*", "[^\"'#]*") + ")";
		
		return new PageProcessor({
			process : function(page){
				try {
					var requests = page.getHtml().links().regex(urlPattern).targets();
					page.addTargets(requests); // add urls to fetch
					page.putField("title", page.getHtml().xpath("//title")); // extract by XPath
					page.putField("html", page.getHtml().toString());
					page.putField("content", page.getHtml().smartContent()); // extract by Readability
				} catch(ex){
					java.lang.System.out.println(ex) ;
				}
			}, 
			
			getSite : function(){
				return site ;
			}
		});
	}, 
	
	this.handle = function(){
		try {
			var spider = Spider.create(this.processor()).scheduler(this.scheduler());
			spider.getSite().setSleepTime(50);
	
			spider.addPipeline(new DebugPipeline()).run();	
		} catch(ex){
			java.lang.System.out.println(ex) ;
		}
	}
} ;